# Generated by Django 3.1.5 on 2021-02-20 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_auto_20210213_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Overview_text', models.TextField(max_length=1000, verbose_name='概要')),
                ('gender', models.CharField(choices=[('男', 'Male'), ('女', 'Female'), ('その他', 'Other')], max_length=10)),
                ('occupation', models.CharField(max_length=100, verbose_name='職業')),
                ('icon', models.ImageField(blank=True, upload_to='None')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
