# Generated by Django 3.1.5 on 2021-02-20 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Overview_text',
            new_name='overview_text',
        ),
    ]
